# Generated by Django 3.0.5 on 2020-05-04 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebanking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='triggered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='onlinebanking.Trigger'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
